backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'artigo'
    label: 'Artigo'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data da publicação', name: 'date', widget: 'datetime' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
      - { label: 'Imagem de destaque', name: 'thumbnail', widget: 'image' }
  - label: 'Páginas'
    name: 'pages'
    files:
      - label: 'Página inicial'
        name: 'home'
        format: 'json'
        file: 'assets/content/pages/home.json'
        fields:
          - { label: 'Título', name: title, widget: string }
          - { label: 'Foto', name: 'thumbnail', widget: 'image' }
          - { label: 'Conteúdo', name: content, widget: markdown }
